/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "boat.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(boat_IMUData, boat_IMUData, AUTO)


PB_BIND(boat_ToFGrid, boat_ToFGrid, 2)


PB_BIND(boat_Detection, boat_Detection, AUTO)


PB_BIND(boat_DetectCommand, boat_DetectCommand, AUTO)


PB_BIND(boat_GpsFix, boat_GpsFix, AUTO)


PB_BIND(boat_GpsCoordinate, boat_GpsCoordinate, AUTO)


PB_BIND(boat_SensorSnapshot, boat_SensorSnapshot, 2)


PB_BIND(boat_MotorCommand, boat_MotorCommand, AUTO)


PB_BIND(boat_WinchCommand, boat_WinchCommand, AUTO)


PB_BIND(boat_SteerCommand, boat_SteerCommand, AUTO)


PB_BIND(boat_MotorStatus, boat_MotorStatus, AUTO)


PB_BIND(boat_ArmCommand, boat_ArmCommand, AUTO)


PB_BIND(boat_ServoPowerCommand, boat_ServoPowerCommand, AUTO)


PB_BIND(boat_SystemStatus, boat_SystemStatus, AUTO)


PB_BIND(boat_BoatMessage, boat_BoatMessage, 4)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

