/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "boat.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(boat_IMUData, boat_IMUData, AUTO)


PB_BIND(boat_ToFGrid, boat_ToFGrid, 2)


PB_BIND(boat_Detection, boat_Detection, AUTO)


PB_BIND(boat_DetectCommand, boat_DetectCommand, AUTO)


PB_BIND(boat_SensorSnapshot, boat_SensorSnapshot, 2)


PB_BIND(boat_MotorCommand, boat_MotorCommand, AUTO)


PB_BIND(boat_SystemStatus, boat_SystemStatus, AUTO)


PB_BIND(boat_BoatMessage, boat_BoatMessage, 2)



